version: 2
jobs:
  lint:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:10.15.3
    environment:
      TZ: /usr/share/zoneinfo/Asia/Tokyo
    steps:
      - checkout
      - restore_cache:
          key: ts-rpa-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Lint
          command: npm run lint
      - save_cache:
          key: ts-rpa-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/workspace/node_modules
  test:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:10.15.3-browsers
    environment:
      TZ: /usr/share/zoneinfo/Asia/Tokyo
    steps:
      - checkout
      - restore_cache:
          key: ts-rpa-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Test
          command: npm test
      - run:
          name: Coverage
          command: npm run coverage
      - save_cache:
          key: ts-rpa-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/workspace/node_modules
workflows:
  version: 2
  lint-and-test:
    jobs:
      - lint
      - test:
          requires:
            - lint
